---
# CMF REST Class - Connection between CFK and CMF
# See: https://docs.confluent.io/operator/current/co-manage-flink.html
apiVersion: platform.confluent.io/v1beta1
kind: CMFRestClass
metadata:
  name: default
  namespace: confluent
spec:
  cmfRest:
    endpoint: http://cmf:80
---
# Flink Environment - Default configuration for Flink applications
apiVersion: platform.confluent.io/v1beta1
kind: FlinkEnvironment
metadata:
  name: flink-env
  namespace: confluent
spec:
  kubernetesNamespace: confluent
  flinkApplicationDefaults:
    metadata:
      labels:
        app.kubernetes.io/part-of: confluent-platform
    spec:
      flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
        rest.profiling.enabled: "true"
  cmfRestClassRef:
    name: default
    namespace: confluent
---
# Sample Flink Application - State Machine Example
# Demonstrates a running Flink job managed by CFK through CMF
apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: state-machine-example
  namespace: confluent
spec:
  flinkEnvironment: flink-env
  image: confluentinc/cp-flink:1.19.1-cp1
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1200m"
      cpu: 1
  taskManager:
    resource:
      memory: "1200m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    state: running
    parallelism: 2
    upgradeMode: stateless
  cmfRestClassRef:
    name: default
    namespace: confluent
