---
# Sample Kafka Streams Application Deployment
# This represents a custom Kafka Streams application managed via GitOps
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageview-enricher
  namespace: confluent
  labels:
    app: pageview-enricher
    component: kstreams
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pageview-enricher
  template:
    metadata:
      labels:
        app: pageview-enricher
        component: kstreams
    spec:
      containers:
        - name: pageview-enricher
          # Demo Kafka Streams consumer - in production replace with your JAR
          image: confluentinc/cp-kafka:8.1.0
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting Kafka Streams demo consumer..."
              echo "Application ID: $APPLICATION_ID"
              echo "Reading from: $INPUT_TOPIC"
              
              # Simple consumer that reads and logs enriched pageviews
              kafka-console-consumer \
                --bootstrap-server $BOOTSTRAP_SERVERS \
                --topic $INPUT_TOPIC \
                --group $APPLICATION_ID \
                --property print.key=true \
                --property print.timestamp=true \
                2>&1 | while read line; do
                  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Processed: $line"
                done
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SCHEMA_REGISTRY_URL
              value: http://schemaregistry:8081
            - name: APPLICATION_ID
              value: pageview-enricher-v1
            - name: INPUT_TOPIC
              value: ENRICHED_PAGEVIEWS
            - name: OUTPUT_TOPIC
              value: processed-pageviews
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
# ConfigMap for Kafka Streams configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kstreams-config
  namespace: confluent
data:
  streams.properties: |
    application.id=pageview-enricher-v1
    bootstrap.servers=kafka:9092
    schema.registry.url=http://schemaregistry:8081
    default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde=io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    num.stream.threads=2
    commit.interval.ms=1000
    cache.max.bytes.buffering=10485760
